export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const CLEAR_USER = 'CLEAR_USER'
export const GET_USER_REPS = 'GET_USER_REPS'
export const GET_USER = 'GET_USER'
export const GET_REPO = 'GET_REPO' 
export const SEARCH_USERS = 'SEARCH_USERS'
export const SEARCH_REPOS = 'SEARCH_REPOS'
export const SET_LOADING = 'SET_LOADING'
export const SET_REPOS_SEARCH = 'SET_REPOS_SEARCH'
export const SET_USERS_SEARCH = 'SET_USERS_SEARCH'
export const GET_PREV_REQUEST = 'GET_PREV_REQUEST'

